### ISSUE TITLE
使用说明可否再详细点呢

### ISSUE THREAD

**Issue by 821733497** [lblblong/nat-utools#1]
用过自带老的内网穿透，现在已经下架了，你这个我已经安装好了，但是还没会用

**Comment by lblblong** [comment]
安装后打开，点击右下角加号，然后输入本地服务监听的端口号就可以了

比如你本地启动了一个 react 项目在 3000 端口，那就点击加号然后输入端口号为 3000，然后就可以得到一个可以给外网访问的地址了

和之前官方的内网穿透使用是差不多的，就是交互逻辑变了

**Comment by linfeng-meng** [comment]
在哪里下载有链接么，内网穿透NAT-1.0.0.upx这个版本不行啊 无法删除无法修改 也连接不上
![image](https://user-images.githubusercontent.com/63132748/127999386-dc95ef03-5268-48e4-b779-17b8a7865cff.png)

**Comment by lblblong** [comment]
> 在哪里下载有链接么，内网穿透NAT-1.0.0.upx这个版本不行啊 无法删除无法修改 也连接不上
> ![image](https://user-images.githubusercontent.com/63132748/127999386-dc95ef03-5268-48e4-b779-17b8a7865cff.png)

这应该是bug，我看下

**Comment by lblblong** [comment]
@linfeng-meng 感觉是你的网络问题，一直处在连接中，你翻墙试试

https://github.com/lblblong/nat-utools/files/6928191/NAT-1.1.0.zip
可以使用这个版本，加上了状态，连接中也可以删除

**Comment by lblblong** [comment]
@linfeng-meng 抱歉，一直连接不上确实是程序问题，因为我最近都没有用内网穿透，所以没看，刚刚才处理..

这个版本可以了 https://github.com/lblblong/nat-utools/releases/download/v1.2.0/NAT-1.2.0.upx
