### ISSUE TITLE
manjaro开启成功但是访问不到

### ISSUE THREAD

**Issue by manton94** [lblblong/nat-utools#10]
一直是404
大佬可以抽空看看吗
![图片](https://user-images.githubusercontent.com/46070956/146338809-837300ff-267a-41f5-8eb2-e68630ba43e4.png)
![图片](https://user-images.githubusercontent.com/46070956/146338883-e4742d72-07a6-4333-a219-c4d70997b139.png)

**Comment by lblblong** [comment]
你本地访问 http://localhost:9092/swagger-ui/index.html 可以访问到吗

**Comment by manton94** [comment]
可以的

**Comment by manton94** [comment]
我找到问题了，我开了全局代理，关了就好了

**Comment by lblblong** [comment]
👍
