### ISSUE TITLE
如何绕过页面提示？

### ISSUE THREAD

**Issue by gjthbc** [lblblong/nat-utools#15]
Friendly Reminder
This website is served via a localtunnel. This is just a reminder to always check the website address you're giving personal, financial, or login details to is actually the real/official website.

Phishing pages often look similar to pages of known banks, social networks, email portals or other trusted institutions in order to acquire personal information such as usernames, passwords or credit card details.

Please proceed with caution.

If you're the developer...
You and other visitors will only see this page from a standard web browser once per IP every 7 days.

Webhook, IPN, and other non-browser requests "should" be directly tunnelled to your localhost. If your webhook/ipn provider happens to send requests using a real browser user-agent header, those requests will unfortunately also be blocked / be forced to see this tunnel reminder page. FYI, this page returns a 401 HTTP Status.

Options to bypass this page:
Set and send a Bypass-Tunnel-Reminder request header (its value can be anything).
or, Set and send a custom / non-standard browser User-Agent request header.
This localtunnel session is sponsored by: Tunez.com - music discovery made easy

**Comment by lblblong** [comment]
似乎是无法跳过的，除非 client 那边的浏览器主动在请求头上添加了 Bypass-Tunnel-Reminder，不然都会展示这个页面

**Comment by yanmw** [comment]
访问你的人在请求头上多加一个参数：Bypass-Tunnel-Reminder，值的随便。
