### ISSUE TITLE
你好，插件市场搜不到呢。

### ISSUE THREAD

**Issue by Famine-Life** [lblblong/nat-utools#3]
你好，插件市场搜不到呢。另外服务端有开源的么

**Comment by lblblong** [comment]
嗯，因为 utools 上架此类插件有法律风险，所以给拒了，只能在 release 页下载了：
https://github.com/lblblong/nat-utools/releases/download/v1.2.0/NAT-1.2.0.upx

这个的内网穿透服务是由 localtunnel 提供的，我只是包了一层界面，所以是没有服务端代码的

**Comment by Famine-Life** [comment]
好嘞。
