### ISSUE TITLE
希望适配Mac端

### ISSUE THREAD

**Issue by zwsn** [lblblong/nat-utools#4]

**Comment by lblblong** [comment]
应该是支持的，是 utools 不能安装这个插件吗，还是有报错信息啥的

**Comment by lblblong** [comment]
你试下这个可不可以：https://github.com/lblblong/nat-utools/releases/download/v1.2.1/NAT-1.2.1.upx

**Comment by zwsn** [comment]
看到了更新，已经安装了,安装成功但是呼出时面板为空白，什么都不显示

**Comment by zwsn** [comment]
![image](https://user-images.githubusercontent.com/42889307/132101413-14c6ede7-6d65-47ca-bd1a-92976ac5dacd.png)

**Comment by zwsn** [comment]
utools版本2.1.0

**Comment by lblblong** [comment]
我这边没有 mac 环境，测试不到。。

**Comment by lblblong** [comment]
下载这个试试：https://github.com/lblblong/nat-utools/releases/tag/v1.2.2

之前应该是 bug。。，因为我也一直没用，还以为是 mac 端的问题，原来是打包的问题，你用这里的安装方法安装一下，应该就可以了

**Comment by zwsn** [comment]
非常感谢回复，按照操作确实出现界面了，但是添加端口后一直处于启动中状态，蓝色指示灯一直闪烁，日志一直显示的是启动中
![image](https://user-images.githubusercontent.com/42889307/133771678-12efeb0e-ad50-4a55-a8a9-981c3d2478be.png)

**Comment by zwsn** [comment]
并且点击关闭服务和删除服务均无反应

**Comment by lblblong** [comment]
最后再相信我一次，这回应该是真行了。。。

https://github.com/lblblong/nat-utools/releases/tag/v1.2.3

**Comment by zwsn** [comment]
确实可以了，非常感谢

**Comment by lblblong** [comment]
太好了，之前一直也有人反馈说用不了，因为我很少用，而且本地运行没问题，就没处理，今天终于找到问题了。。。，有些本地依赖没有打包到插件里。。
