### ISSUE TITLE
启动服务后标题消失

### ISSUE THREAD

**Issue by Codeniu** [lblblong/nat-utools#5]
启动前
![image](https://user-images.githubusercontent.com/28432016/136652706-e89e9797-fe5e-4b94-a61c-e73c13365719.png)

启动后
![image](https://user-images.githubusercontent.com/28432016/136652726-12e7fc3f-c323-4927-8c42-42d0c51d5e04.png)

**Comment by lblblong** [comment]
完全退出插件，多试几次还这样吗

**Comment by Codeniu** [comment]
原来是主题的原因，深色主题下颜色跟背景颜色重复了
![image](https://user-images.githubusercontent.com/28432016/136652953-ea0ba63b-e6c8-43ce-8a57-311dd09a170e.png)
