### ISSUE TITLE
定义子域名 api   状态一直在闪烁

### ISSUE THREAD

**Issue by ice-leng** [lblblong/nat-utools#6]
![image](https://user-images.githubusercontent.com/7506787/136801156-f3b1ae7b-3eb7-47f9-bd8b-99eaf24a1ac8.png)
![image](https://user-images.githubusercontent.com/7506787/136801210-a18b42a2-3443-43e8-8f46-c47d154ca4c3.png)
并且 无法编辑

**Comment by lblblong** [comment]
那如果不设置子域名能正常启动吗

**Comment by ice-leng** [comment]
能的

**Comment by lblblong** [comment]
今天问题也还存在吗

**Comment by ice-leng** [comment]
情况是这样，  自定义 子域名 api  还是那样
但是 你换一个 子域名 比如 api-test  就好了

**Comment by lblblong** [comment]
那我知道问题了，子域名长度有限制的，4-64个字符好像，但是有些东西被封装在了 localtunnel 内部，错误没有抛出来，没办法友好的提示，我得花点时间改动一下 localtunnel

**Comment by ice-leng** [comment]
话说    网页   访问 那个 确认页面 怎么屏蔽掉呢

**Comment by lblblong** [comment]
如果是用浏览器打开，那个确认页面屏蔽不掉的，除非能够自定义浏览器的 User-Agen，浏览器之外一般不会有那个页面，可以放心请求接口

**Comment by lblblong** [comment]
https://github.com/lblblong/nat-utools/releases/tag/v2.0.0

新版本增加了错误的提示
